# escape=`

# Offline
# FROM  mcr.microsoft.com/windows/nanoserver:2004
# LABEL maintainer="kkbruce"

# RUN mkdir c:\redis_data
# COPY Redis /Redis
# ADD redis.docker-sentinel.conf /Redis
# WORKDIR /Redis
# EXPOSE 26379

# CMD ["redis-server.exe", "redis.docker-sentinel.conf", "--sentinel"]

# Online
FROM mcr.microsoft.com/powershell:nanoserver-2004
LABEL maintainer="kkbruce" Version="4.0.14.2"

RUN mkdir c:\redis_data
# zip source: https://github.com/tporadowski/redis
RUN pwsh -Command `
	$ErrorActionPreference = 'Stop'; `
	Invoke-WebRequest -Method Get -Uri https://github.com/tporadowski/redis/releases/download/v4.0.14.2/Redis-x64-4.0.14.2.zip -OutFile c:\redis.zip ; `
	Expand-Archive -Path c:\redis.zip -DestinationPath c:\redis ; `
	Remove-Item c:\redis.zip -Force
ADD redis.docker-sentinel.conf /redis
WORKDIR /redis
EXPOSE 26379

CMD ["redis-server.exe", "redis.docker-sentinel.conf", "--sentinel"]