# escape=`

FROM  mcr.microsoft.com/windows/nanoserver:1909
LABEL maintainer="kkbruce"

RUN mkdir c:\redis_data
COPY Redis /Redis
ADD redis.docker-sentinel.conf /Redis
WORKDIR /Redis
EXPOSE 26379

CMD ["redis-server.exe", "redis.docker-sentinel.conf", "--sentinel"]