version: '3.7'
services:
  master:
    image: "kkbruce/redis:master-4.0.14.2-aof-nanoserver-1909"
    ports:
      - 6379:6379
    hostname: redis-master
    volumes:
      - redis-data:c:\redis_data
    networks:
      redis-net:
        ipv4_address: 10.10.10.10
    restart: unless-stopped

  slave:
    image: "kkbruce/redis:slave-4.0.14.2-aof-nanoserver-1909"
    ports:
      - 6380:6380
    hostname: redis-slave
    volumes:
      - redis-data:c:\redis_data
    networks:
      - redis-net
    restart: unless-stopped
    depends_on:
      - master

  sentinel:
    image: "kkbruce/redis:sentinel-4.0.14.2-aof-nanoserver-1909"
    ports:
      - 26379:26379
    hostname: redis-sentinel
    volumes:
      - redis-data:c:\redis_data
    networks:
      - redis-net
    restart: unless-stopped
    depends_on:
      - master
      - slave

# networks:
#   redis-net:
#     external: true
#     name: redis-net

networks:
  redis-net:
    ipam:
      driver: windows
      config: 
        - subnet: "10.10.10.0/24"
volumes:
  redis-data: