# escape=`

# Offline
# FROM  mcr.microsoft.com/windows/nanoserver:1909
# LABEL maintainer="kkbruce"

# RUN mkdir c:\redis_data
# COPY Redis /Redis
# ADD redis.docker-slave.conf /Redis
# WORKDIR /Redis
# EXPOSE 6380

# CMD ["redis-server.exe", "redis.docker-slave.conf"]

# Online
FROM mcr.microsoft.com/powershell:nanoserver-1909
LABEL maintainer="kkbruce" Version="5.0.9"

RUN mkdir c:\redis_data
RUN pwsh -Command `
	$ErrorActionPreference = 'Stop'; `
	Invoke-WebRequest -Method Get -Uri https://github.com/tporadowski/redis/releases/download/v5.0.9/Redis-x64-5.0.9.zip -OutFile c:\redis.zip ; `
	Expand-Archive -Path c:\redis.zip -DestinationPath c:\redis ; `
	Remove-Item c:\redis.zip -Force
ADD redis.docker-slave.conf /redis
WORKDIR /redis
EXPOSE 6380

CMD ["redis-server.exe", "redis.docker-slave.conf"]